name: Build & Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Set up application.properties for testing
      run: |
        mkdir -p ./OrariAperti/backend/src/test/resources
        touch ./OrariAperti/backend/src/test/resources/application.properties
        echo "# Test Configuration" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "## General" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "spring.application.name=${SPRING_APPLICATION_NAME:OrariAperti}" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "## Database" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL" >> ./OrariAperti/backend/src/test/resources/application.properties
        echo "spring.datasource.driverClassName=org.h2.Driver" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "spring.datasource.username=sa" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "spring.datasource.password=" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "spring.jpa.hibernate.ddl-auto=create-drop" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "spring.sql.init.mode=never" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "# CORS and Redirect Configuration" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "frontend.url=${FRONTEND_URL:http://localhost:3000}" > ./OrariAperti/backend/src/test/resources/application.properties
        echo "" > ./OrariAperti/backend/src/test/resources/application.properties

    - name: Test with Maven
      run: mvn test
      working-directory: ./OrariAperti/backend

    - name: Build with Maven
      run: mvn -DskipTests package
      working-directory: ./OrariAperti/backend
